create table tb_schedule (
    id int8 generated by default as identity check (id > 0),
    curr_date timestamp not null,
    schedule_date timestamp not null check (schedule_date > curr_date),
    service varchar(150) not null,
    user_id int8 check (user_id > 0),
    primary key (id)
);

create table tb_user (
    id int8 generated by default as identity check (id > 0),
    email varchar(150) not null,
    name varchar(150) not null,
    password varchar(32) not null,
    primary key (id)
);

alter table if exists tb_schedule
   add constraint UK_8m3bkw8vhv6ny9eh96vq7pqsv unique (schedule_date);

alter table if exists tb_user
   add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);

alter table if exists tb_user
   add constraint UK_jus3xa0l3009mkpbt9i5ilxx3 unique (name);

alter table if exists tb_schedule
   add constraint FK3cym2pc44bkcb5gtb6liqit41
   foreign key (user_id)
   references tb_user;

CREATE VIEW Schedules_View AS
	SELECT u.name, s.schedule_date, s.service
	FROM tb_user as u INNER JOIN tb_schedule as s
	ON u.id = s.user_id;

INSERT INTO tb_user(name, email, password) VALUES ('Abigail', 'aby@gmail.com', 'aby123');
INSERT INTO tb_user(name, email, password) VALUES ('Arthur', 'arthur@gmail.com', '123');
INSERT INTO tb_user(name, email, password) VALUES ('Nathanael', 'nate@gmail.com', 'nate123');

INSERT INTO tb_schedule(user_id, curr_date, schedule_date, service) VALUES (1, '2022-05-22 19:22:25', '2022-06-23 14:00:00', 'Web Project with React and Next.js');
INSERT INTO tb_schedule(user_id, curr_date, schedule_date, service) VALUES (1, '2022-06-20 11:26:45', '2022-08-22 11:30:00', 'Mobile Project with React Native');
INSERT INTO tb_schedule(user_id, curr_date, schedule_date, service) VALUES (2, '2022-07-01 23:55:20', '2022-07-03 09:30:00', 'Backend Project with Spring Boot');
INSERT INTO tb_schedule(user_id, curr_date, schedule_date, service) VALUES (2, '2022-07-13 01:13:12', '2022-08-01 08:00:00', 'IoT Project');
